config/routes.rb
Rails.application.routes.draw do
  root 'baskets#new'

  resources :baskets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :items

=begin
scanning the code of a product creates an item by finding the equivilant
row in the catalog entry table. It creates this new item and calculates the
VAT that will be applied, storing this in the item entry. The item is
given the id of the current basket.
=end

  def scan(product_code)
    catalog_entries = CatalogEntry.where(product_code: product_code)
    if catalog_entries.count > 1
      raise 'Multiple catalog entries with same product code found'
    elsif catalog_entries.count < 1
      raise 'Invalid code given, no item added to basket'
    else
      catalog_entry = catalog_entries.first
      self.items.create!(catalog_entry: catalog_entry)
    end
  end

  #calculates total price of items before any discounts or VAT.
  def subtotal
    if items.exists?
      items.map{|x| x.price}.sum
    else
      return 0
    end
  end

  #sums the total vat of all items in the basket
  def total_vat
    if items.exists?
      items.map{|x| x.vat}.sum
    else
      return 0
    end
  end

  #discount of £5 given for every second flag
  def flag_discount
    list = items.select{|x| x.product_code == 1}
    flag_count = list.count
    (flag_count/2) * 5
  end

  #if subtotal + VAT - flagdiscount is over £70, %12 discount is applied
  def total_discount
    total = subtotal + total_vat - flag_discount
    if total > 70
      return (total) * 0.12
    else
      return 0
    end
  end

  #final total, including VAT and discounts. Rounded to 2 decimal places
  def total
    (subtotal + total_vat - flag_discount - total_discount)
  end

end

app/models/catalog_entry.rb
class CatalogEntry < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :basket
  belongs_to :catalog_entry

  def name
    catalog_entry.name
  end

  def product_code
    catalog_entry.product_code
  end

  def price
    catalog_entry.price
  end

  def vat
    catalog_entry.price * catalog_entry.vat_rate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  include ActionView::Helpers::NumberHelper


  def new
    @basket = Basket.new

    @sub = number_to_currency(@basket.subtotal + @basket.total_vat, unit: '£')
  end

  def create
    @basket = Basket.create
    @basket.scan(params[:item].to_i)
    redirect_to action: 'edit', id: @basket.id
  end

  def edit
    @basket = Basket.find(params[:id])
    @sub = number_to_currency(@basket.subtotal + @basket.total_vat, unit: '£')
  end

  def update
    @basket = Basket.find(params[:id])
    @basket.scan(params[:item].to_i)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/baskets/_basket_content.html.haml
.content.container-fluid
  .row.header
    %h1 ScotBasket

  .row.top_text
    %p.basket_text Select an item to add to the basket.
    =form_for @basket do |f|
      .basket_select.col-sm-offset-1
        .item_select.col-sm-3.col-sm-offset-3
          %select{name: 'item'}
            %option{value: 1} Scotland Flag
            %option{value: 2} Child's Car Seat
            %option{value: 3} Magnetic Wrist Band
        .item_submit.col-sm-3
          =f.submit 'Add Item'
  .row
    .total
      %p= "Subtotal (inc VAT): #{@sub}"
      -if @basket.flag_discount > 0
        %p= "Flag Discount: #{number_to_currency(@basket.flag_discount, unit: '£',)}"
      -if @basket.total_discount > 0
        %p= "12% Discount off cost so far: #{number_to_currency(@basket.total_discount, unit: '£')}"
      %p.final_total= "Final Total: #{number_to_currency(@basket.total, unit: '£')}"
  .row
    .summary.col-xs-12
      -if @basket.items.count > 0
        %h3 Summary of Items
        %br
        .row
          .item_summary
            %table.table-bordered.table
              %tr
                %th Item Name
                %th Price
                %th VAT
              - @basket.items.each do |i|
                =render partial: 'item_summary', locals: {item: i}
  %br
  .row.col-sm-offset-1
    .clear_basket.col-xs-2.col-sm-offset-6
      =link_to "New Basket", new_basket_path

app/views/baskets/_item_summary.html.haml
%tr
  %td= item.name.split('_').map(&:capitalize).join(' ')
  %td= number_to_currency(item.price, unit: '£')
  %td= number_to_currency(item.vat, unit: '£')

app/views/baskets/edit.html.haml
=render partial: 'basket_content'

app/views/baskets/new.html.haml
=render partial: 'basket_content'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ScotBasket
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield